name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip3 install --upgrade pip3
        pip3 install beautifulsoup4
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: chmod scraper
      run: |
        chmod +x scraper.py
    - name: run scraper
      run: |
        ./scraper.py
