name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools beautifulsoup4
    - name: chmod scraper
      run: |
        chmod +x scraper.py
    - name: run scraper
      run: |
        ./scraper.py
