name: Python application

on:
  push:
    branches: [ master ]
  # schedule:
    # - cron:  "*/5 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools beautifulsoup4
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          bs4
          beautifulsoup4
          requests
    - name: chmod scraper
      run: |
        chmod +x scraper.py
    - name: run scraper
      run: |
        python3 ./scraper.py
    - name: Upload items
      uses: actions/upload-artifact@v1
      with:
        name: items.csv
        path: items.csv
      if: ${{ always() }}
